[package]
name = "memsocket"
version = "0.1.0"
authors = ["kail"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
bytes = "1"
once_cell = "1.3.1"
