[package]
name = "crypto-derive"
version = "0.1.0"
authors = ["kail"]
edition = "2021"


[lib]
proc_macro = true

[dependencies]
syn = { version = "1.0", features = ["derive"] }
quote = "1.0"
proc-macro2 = "1.0"
